// userResponses
export const RECORD_COLLABORATIVE = "INREASE_COLLABORATIVE";
export const RECORD_INDEPENDENT = "INREASE_INDEPENDENT";
export const RECORD_FORMAL = "INREASE_FORMAL";
export const RECORD_CASUAL = "INREASE_CASUAL";
export const RECORD_TASK_ORIENTED = "INREASE_TASK_ORIENTED";
export const RECORD_IMPROVISOR = "INREASE_IMPROVISOR";
export const RECORD_BACK_OFFICE = "INREASE_BACK_OFFICE";
export const RECORD_CLIENT_FACING = "INREASE_CLIENT_FACING";

// questions
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const NEXT_QUESTION_SET = "NEXT_QUESTION_SET";
export const PREVIOUS_QUESTION_SET = "PREVIOUS_QUESTION_SET";
export const CALCULATE_RESULTS = "CALCULATE_RESULTS";
