// questions
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const NEXT_QUESTION_SET = "NEXT_QUESTION_SET";
export const PREVIOUS_QUESTION_SET = "PREVIOUS_QUESTION_SET";
export const CALCULATE_RESULTS = "CALCULATE_RESULTS";
export const START_EVALUATOR_REQUEST = "START_EVALUATOR_REQUEST";
export const LOAD_EVALUATOR_SUCCESS = "LOAD_EVALUATOR_SUCCESS";
export const QUESTION_AJAX_FAILURE = "QUESTION_AJAX_FAILURE";
export const LOAD_EVALUATOR_REQUEST = "LOAD_EVALUATOR_REQUEST";

// profile
export const CREATE_APPLICANT_REQUEST = "CREATE_APPLICANT_REQUEST";
export const UPDATE_APPLICANT_REQUEST = "UPDATE_APPLICANT_REQUEST";
export const LOAD_APPLICANT_REQUEST = "LOAD_APPLICANT_REQUEST";
export const LOAD_APPLICANT_SUCCESS = "LOAD_APPLICANT_SUCCESS";
export const CREATE_EDUCATION_EXPERIENCE_REQUEST =
  "CREATE_EDUCATION_EXPERIENCE_REQUEST";
export const CREATE_EDUCATION_EXPERIENCE_SUCCESS =
  "CREATE_EDUCATION_EXPERIENCE_SUCCESS";
export const DELETE_EDUCATION_EXPERIENCE_REQUEST =
  "DELETE_EDUCATION_EXPERIENCE_REQUEST";
export const DELETE_EDUCATION_EXPERIENCE_SUCCESS =
  "DELETE_EDUCATION_EXPERIENCE_SUCCESS";
export const CREATE_JOB_EXPERIENCE_REQUEST = "CREATE_JOB_EXPERIENCE_REQUEST";
export const CREATE_JOB_EXPERIENCE_SUCCESS = "CREATE_JOB_EXPERIENCE_SUCCESS";
export const DELETE_JOB_EXPERIENCE_REQUEST = "DELETE_JOB_EXPERIENCE_REQUEST";
export const DELETE_JOB_EXPERIENCE_SUCCESS = "DELETE_JOB_EXPERIENCE_SUCCESS";
export const PROFILE_AJAX_FAILURE = "PROFILE_AJAX_FAILURE";

// skills
export const LOAD_SKILLS_REQUEST = "LOAD_SKILLS_REQUEST";
export const LOAD_SKILLS_SUCCESS = "LOAD_SKILLS_SUCCESS";
export const ADD_SKILLS_TO_APPLICANT_REQUEST =
  "ADD_SKILLS_TO_APPLICANT_REQUEST";
export const ADD_SKILLS_TO_APPLICANT_SUCCESS =
  "ADD_SKILLS_TO_APPLICANT_SUCCESS";
export const REMOVE_SKILL_FROM_APPLICANT_REQUEST =
  "REMOVE_SKILL_FROM_APPLICANT_REQUEST";
export const REMOVE_SKILL_FROM_APPLICANT_SUCCESS =
  "REMOVE_SKILL_FROM_APPLICANT_SUCCESS";
export const SKILL_AJAX_FAILURE = "SKILL_AJAX_FAILURE";

// industries
export const LOAD_INDUSTRIES_REQUEST = "LOAD_INDUSTRIES_REQUEST";
export const LOAD_INDUSTRIES_SUCCESS = "LOAD_INDUSTRIES_SUCCESS";
export const ADD_INDUSTRIES_TO_APPLICANT_REQUEST =
  "ADD_INDUSTRIES_TO_APPLICANT_REQUEST";
export const ADD_INDUSTRIES_TO_APPLICANT_SUCCESS =
  "ADD_INDUSTRIES_TO_APPLICANT_SUCCESS";
export const INDUSTRY_AJAX_FAILURE = "INDUSTRY_AJAX_FAILURE";

// auth
export const GET_ME_REQUEST = "GET_ME_REQUEST";
export const GET_ME_SUCCESS = "GET_ME_SUCCESS";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const AUTH_AJAX_FAILURE = "AUTH_AJAX_FAILURE";

// industrySectors
export const LOAD_INDUSTRY_SECTORS_REQUEST = "LOAD_INDUSTRY_SECTORS_REQUEST";
export const LOAD_INDUSTRY_SECTORS_SUCCESS = "LOAD_INDUSTRY_SECTORS_SUCCESS";
export const ADD_INDUSTRY_SECTORS_TO_APPLICANT_REQUEST =
  "ADD_INDUSTRY_SECTORS_TO_APPLICANT_REQUEST";
export const ADD_INDUSTRY_SECTORS_TO_APPLICANT_SUCCESS =
  "ADD_INDUSTRY_SECTORS_TO_APPLICANT_SUCCESS";
export const REMOVE_INDUSTRY_SECTOR_FROM_APPLICANT_REQUEST =
  "REMOVE_INDUSTRY_SECTOR_FROM_APPLICANT_REQUEST";
export const REMOVE_INDUSTRY_SECTOR_FROM_APPLICANT_SUCCESS =
  "REMOVE_INDUSTRY_SECTOR_FROM_APPLICANT_SUCCESS";
export const INDUSTRY_SECTOR_AJAX_FAILURE = "INDUSTRY_SECTOR_AJAX_FAILURE";

// skills
export const LOAD_CERTIFICATIONS_REQUEST = "LOAD_CERTIFICATIONS_REQUEST";
export const LOAD_CERTIFICATIONS_SUCCESS = "LOAD_CERTIFICATIONS_SUCCESS";
export const ADD_CERTIFICATIONS_TO_APPLICANT_REQUEST =
  "ADD_CERTIFICATIONS_TO_APPLICANT_REQUEST";
export const ADD_CERTIFICATIONS_TO_APPLICANT_SUCCESS =
  "ADD_CERTIFICATIONS_TO_APPLICANT_SUCCESS";
export const REMOVE_CERTIFICATION_FROM_APPLICANT_REQUEST =
  "REMOVE_CERTIFICATION_FROM_APPLICANT_REQUEST";
export const REMOVE_CERTIFICATION_FROM_APPLICANT_SUCCESS =
  "REMOVE_CERTIFICATION_FROM_APPLICANT_SUCCESS";
export const CERTIFICATION_AJAX_FAILURE = "CERTIFICATION_AJAX_FAILURE";

// applicants
export const LOAD_APPLICANTS_REQUEST = "LOAD_APPLICANTS_REQUEST";
export const LOAD_APPLICANTS_SUCCESS = "LOAD_APPLICANTS_SUCCESS";
export const APPLICANT_AJAX_FAILURE = "APPLICANTS_AJAX_FAILURE";
