// questions
export const ANSWER_QUESTION = "ANSWER_QUESTION";
export const NEXT_QUESTION_SET = "NEXT_QUESTION_SET";
export const PREVIOUS_QUESTION_SET = "PREVIOUS_QUESTION_SET";
export const CALCULATE_RESULTS = "CALCULATE_RESULTS";
export const START_EVALUATOR_REQUEST = "START_EVALUATOR_REQUEST";
export const LOAD_EVALUATOR_SUCCESS = "LOAD_EVALUATOR_SUCCESS";
export const QUESTION_AJAX_FAILURE = "QUESTION_AJAX_FAILURE";
export const LOAD_EVALUATOR_REQUEST = "LOAD_EVALUATOR_REQUEST";

// profile
export const CREATE_APPLICANT_REQUEST = "CREATE_APPLICANT_REQUEST";
export const UPDATE_APPLICANT_REQUEST = "UPDATE_APPLICANT_REQUEST";
export const LOAD_APPLICANT_REQUEST = "LOAD_APPLICANT_REQUEST";
export const LOAD_APPLICANT_SUCCESS = "LOAD_APPLICANT_SUCCESS";
export const PROFILE_AJAX_FAILURE = "PROFILE_AJAX_FAILURE";
